import { useCallback,useState } from 'react';
import { Alert,Pressable,Text,View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { transferService,walletService } from '@/dichvu';
import type { Transfer,Wallet } from '@/kieudulieu';
import { Button,Card,EmptyState,Field,Header,Loading,Screen } from '@/thanhphan/dungchung/UI';
import { Colors } from '@/hangso/colors';
import { apiMessage,formatCurrency,formatDate,today } from '@/tienich/dinhdang';

function WalletChoice({wallet,selected,onPress}:{wallet:Wallet;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={{padding:11,borderRadius:12,borderWidth:1,borderColor:selected?Colors.primary:Colors.border,backgroundColor:selected?Colors.primarySoft:Colors.surface}}><Text style={{fontWeight:'700',color:selected?Colors.primary:Colors.text}}>{wallet.name}</Text><Text style={{fontSize:12,color:Colors.muted}}>{formatCurrency(wallet.current_balance)}</Text></Pressable>}

export default function TransferScreen(){
  const [wallets,setWallets]=useState<Wallet[]>([]);const [items,setItems]=useState<Transfer[]>([]);const [fromId,setFromId]=useState<number>();const [toId,setToId]=useState<number>();const [amount,setAmount]=useState('');const [description,setDescription]=useState('');const [date,setDate]=useState(today());const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{const [walletResult,transferResult]=await Promise.all([walletService.list(),transferService.list()]);setWallets(walletResult.data);setItems(transferResult.data);setFromId(current=>current??walletResult.data[0]?.id);setToId(current=>current??walletResult.data[1]?.id);}finally{setLoading(false)}},[]);
  useFocusEffect(useCallback(()=>{load()},[load]));
  const submit=async()=>{if(!fromId||!toId||fromId===toId||Number(amount)<=0)return Alert.alert('Dữ liệu chưa hợp lệ','Chọn hai ví khác nhau và nhập số tiền lớn hơn 0.');try{setSaving(true);await transferService.create({from_wallet_id:fromId,to_wallet_id:toId,amount:Number(amount),description,transfer_date:date});setAmount('');setDescription('');Alert.alert('Thành công','Đã chuyển tiền giữa hai ví.');await load();}catch(error){Alert.alert('Không thể chuyển tiền',apiMessage(error));}finally{setSaving(false)}};
  if(loading)return <Screen><Loading/></Screen>;
  return <Screen><Header title="Chuyển tiền" subtitle="Di chuyển tiền an toàn giữa các ví của bạn"/>{wallets.length<2?<EmptyState title="Cần ít nhất hai ví" description="Hãy tạo thêm ví trước khi chuyển tiền."/>:<Card style={{gap:14}}><Text style={{fontWeight:'800',color:Colors.text}}>Từ ví</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{wallets.map(wallet=><WalletChoice key={wallet.id} wallet={wallet} selected={fromId===wallet.id} onPress={()=>setFromId(wallet.id)}/>)}</View><Text style={{fontWeight:'800',color:Colors.text}}>Đến ví</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{wallets.filter(wallet=>wallet.id!==fromId).map(wallet=><WalletChoice key={wallet.id} wallet={wallet} selected={toId===wallet.id} onPress={()=>setToId(wallet.id)}/>)}</View><Field label="Số tiền (VNĐ)" value={amount} onChangeText={setAmount} keyboardType="numeric"/><Field label="Ngày chuyển" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/><Field label="Ghi chú" value={description} onChangeText={setDescription}/><Button title="Xác nhận chuyển tiền" onPress={submit} loading={saving}/></Card>}<Text style={{fontSize:19,fontWeight:'800',color:Colors.text}}>Lịch sử chuyển tiền</Text>{items.length?items.map(item=><Card key={item.id} style={{gap:6}}><Text style={{fontWeight:'800',color:Colors.text}}>{item.from_wallet_name} → {item.to_wallet_name}</Text><Text style={{fontSize:20,fontWeight:'900',color:Colors.primary}}>{formatCurrency(item.amount)}</Text><Text style={{color:Colors.muted}}>{formatDate(item.transfer_date)} · {item.description||'Không có ghi chú'}</Text></Card>):<EmptyState title="Chưa có lần chuyển tiền nào"/>}</Screen>;
}
