const pool=require('../cauhinh/database'); const {requireFields,positiveMoney,assertType}=require('../tienich/validation');
const delta=(type,amount)=>type==='income'?amount:-amount;
async function ownedReference(conn,table,id,userId){const [rows]=await conn.query(`SELECT id${table==='wallets'?', current_balance':''} FROM ${table} WHERE id=? AND user_id=?${table==='wallets'?' FOR UPDATE':''}`,[id,userId]);if(!rows[0]){const e=new Error(table==='wallets'?'Ví không hợp lệ.':'Danh mục không hợp lệ.');e.status=400;throw e;}return rows[0];}
async function validateRefs(conn,body,userId){const wallet=await ownedReference(conn,'wallets',body.wallet_id,userId);const [cats]=await conn.query('SELECT id,type FROM categories WHERE id=? AND user_id=?',[body.category_id,userId]);if(!cats[0]||cats[0].type!==body.type){const e=new Error('Danh mục không phù hợp với loại giao dịch.');e.status=400;throw e;}return wallet;}
async function list(req,res,next){try{const conditions=['t.user_id=?'];const params=[req.user.id];for(const [query,column] of [['type','t.type'],['category_id','t.category_id'],['wallet_id','t.wallet_id']])if(req.query[query]){conditions.push(`${column}=?`);params.push(req.query[query]);}if(req.query.start_date){conditions.push('DATE(t.transaction_date)>=?');params.push(req.query.start_date);}if(req.query.end_date){conditions.push('DATE(t.transaction_date)<=?');params.push(req.query.end_date);}if(req.query.search){conditions.push('(t.description LIKE ? OR c.name LIKE ? OR w.name LIKE ?)');const s=`%${req.query.search}%`;params.push(s,s,s);}const [rows]=await pool.query(`SELECT t.*,w.name wallet_name,c.name category_name,c.icon category_icon FROM transactions t JOIN wallets w ON w.id=t.wallet_id JOIN categories c ON c.id=t.category_id WHERE ${conditions.join(' AND ')} ORDER BY t.transaction_date DESC,t.id DESC`,params);res.json(rows);}catch(e){next(e);}}
async function detail(req,res,next){try{const [rows]=await pool.query('SELECT t.*,w.name wallet_name,c.name category_name,c.icon category_icon FROM transactions t JOIN wallets w ON w.id=t.wallet_id JOIN categories c ON c.id=t.category_id WHERE t.id=? AND t.user_id=?',[req.params.id,req.user.id]);if(!rows[0]){const e=new Error('Không tìm thấy giao dịch.');e.status=404;throw e;}res.json(rows[0]);}catch(e){next(e);}}
async function create(req,res,next){const conn=await pool.getConnection();try{requireFields(req.body,['wallet_id','category_id','type','amount','transaction_date']);assertType(req.body.type);const amount=positiveMoney(req.body.amount);await conn.beginTransaction();await validateRefs(conn,req.body,req.user.id);const [r]=await conn.query('INSERT INTO transactions (user_id,wallet_id,category_id,type,amount,description,transaction_date) VALUES (?,?,?,?,?,?,?)',[req.user.id,req.body.wallet_id,req.body.category_id,req.body.type,amount,req.body.description||null,req.body.transaction_date]);await conn.query('UPDATE wallets SET current_balance=current_balance+? WHERE id=?',[delta(req.body.type,amount),req.body.wallet_id]);await conn.commit();req.params.id=r.insertId;return detail(req,res,next);}catch(e){await conn.rollback();next(e);}finally{conn.release();}}
async function update(req,res,next){const conn=await pool.getConnection();try{requireFields(req.body,['wallet_id','category_id','type','amount','transaction_date']);assertType(req.body.type);const amount=positiveMoney(req.body.amount);await conn.beginTransaction();const [oldRows]=await conn.query('SELECT * FROM transactions WHERE id=? AND user_id=? FOR UPDATE',[req.params.id,req.user.id]);const old=oldRows[0];if(!old){const e=new Error('Không tìm thấy giao dịch.');e.status=404;throw e;}await ownedReference(conn,'wallets',old.wallet_id,req.user.id);await conn.query('UPDATE wallets SET current_balance=current_balance-? WHERE id=?',[delta(old.type,Number(old.amount)),old.wallet_id]);await validateRefs(conn,req.body,req.user.id);await conn.query('UPDATE transactions SET wallet_id=?,category_id=?,type=?,amount=?,description=?,transaction_date=? WHERE id=?',[req.body.wallet_id,req.body.category_id,req.body.type,amount,req.body.description||null,req.body.transaction_date,req.params.id]);await conn.query('UPDATE wallets SET current_balance=current_balance+? WHERE id=?',[delta(req.body.type,amount),req.body.wallet_id]);await conn.commit();return detail(req,res,next);}catch(e){await conn.rollback();next(e);}finally{conn.release();}}
async function remove(req,res,next){const conn=await pool.getConnection();try{await conn.beginTransaction();const [rows]=await conn.query('SELECT * FROM transactions WHERE id=? AND user_id=? FOR UPDATE',[req.params.id,req.user.id]);const old=rows[0];if(!old){const e=new Error('Không tìm thấy giao dịch.');e.status=404;throw e;}await ownedReference(conn,'wallets',old.wallet_id,req.user.id);await conn.query('UPDATE wallets SET current_balance=current_balance-? WHERE id=?',[delta(old.type,Number(old.amount)),old.wallet_id]);await conn.query('DELETE FROM transactions WHERE id=?',[old.id]);await conn.commit();res.status(204).end();}catch(e){await conn.rollback();next(e);}finally{conn.release();}}
module.exports={list,detail,create,update,remove};
