import { useEffect, useMemo, useState } from 'react';
import { api, session } from './api';

const navItems = [
  ['dashboard', '⌂', 'Tổng quan'], ['users', '♙', 'Người dùng'], ['categories', '◇', 'Danh mục'],
  ['notifications', '♢', 'Thông báo'], ['feedback', '◌', 'Phản hồi'], ['statistics', '▥', 'Thống kê'],
  ['account', '○', 'Tài khoản'],
];

const labels = {
  active: 'Đang hoạt động', locked: 'Đã khóa', income: 'Thu nhập', expense: 'Chi tiêu',
  pending: 'Chờ xử lý', processing: 'Đang xử lý', resolved: 'Đã xử lý',
  bug: 'Báo lỗi', suggestion: 'Góp ý', support: 'Hỗ trợ', draft: 'Bản nháp', sent: 'Đã gửi', archived: 'Đã lưu trữ',
};

const formatDate = (value) => value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const initials = (name = 'A') => name.split(' ').slice(-2).map((part) => part[0]).join('').toUpperCase();

function Badge({ value }) { return <span className={`badge badge-${value}`}>{labels[value] || value}</span>; }
function Spinner() { return <div className="loading"><span className="spinner" />Đang tải dữ liệu...</div>; }
function Empty({ children = 'Chưa có dữ liệu' }) { return <div className="empty"><span>◇</span><p>{children}</p></div>; }
function ErrorBox({ error }) { return error ? <div className="error-box">{error}</div> : null; }
function PageTitle({ title, subtitle, action }) { return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }

function Modal({ title, children, onClose, wide = false }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><div className={`modal ${wide ? 'modal-wide' : ''}`} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}>×</button></div>{children}</div></div>;
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ login: '', password: '', remember: true });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); setError(''); setLoading(true);
    try {
      const data = await api.login({ login: form.login.trim(), password: form.password });
      if (data.user.role !== 'admin') throw new Error('Tài khoản này không có quyền quản trị.');
      session.set(data.token, form.remember); onLogin(data.user);
    } catch (err) { session.clear(); setError(err.message); } finally { setLoading(false); }
  };
  return <div className="login-page"><div className="login-visual"><div className="brand-mark">₫</div><div><span className="eyebrow">HỆ THỐNG QUẢN TRỊ</span><h1>Kiểm soát hệ thống<br />trong một màn hình.</h1><p>Theo dõi người dùng, vận hành danh mục và chăm sóc phản hồi một cách rõ ràng.</p></div><div className="visual-note"><b>An toàn & riêng tư</b><span>Không hiển thị mật khẩu, token hoặc số tiền chi tiết của người dùng.</span></div></div><div className="login-panel"><form className="login-card" onSubmit={submit}><div className="mobile-brand"><span>₫</span> Quản trị tài chính</div><span className="eyebrow">CHÀO MỪNG TRỞ LẠI</span><h2>Đăng nhập quản trị</h2><p>Sử dụng tài khoản được cấp quyền admin.</p><ErrorBox error={error} /><label>Tên đăng nhập hoặc email<input autoFocus value={form.login} onChange={(event) => setForm({ ...form, login: event.target.value })} placeholder="Nhập tài khoản" required /></label><label>Mật khẩu<input type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Nhập mật khẩu" required /></label><label className="check"><input type="checkbox" checked={form.remember} onChange={(event) => setForm({ ...form, remember: event.target.checked })} /> Ghi nhớ đăng nhập</label><button className="btn btn-primary btn-block" disabled={loading}>{loading ? 'Đang đăng nhập...' : 'Đăng nhập'}</button><small>Trang này chỉ dành cho quản trị viên hệ thống.</small></form></div></div>;
}

function Shell({ user, section, setSection, onLogout, children }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="shell"><aside className={mobileOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark small">₫</div><div><b>Money Admin</b><span>Quản lý tài chính</span></div></div><nav>{navItems.map(([key, icon, label]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => { setSection(key); setMobileOpen(false); }}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-user"><div className="avatar">{initials(user.full_name)}</div><div><b>{user.full_name}</b><span>Quản trị viên</span></div><button title="Đăng xuất" onClick={onLogout}>↪</button></div></aside><main><header className="topbar"><button className="menu-btn" onClick={() => setMobileOpen(!mobileOpen)}>☰</button><div><b>{navItems.find(([key]) => key === section)?.[2]}</b><span> / Trung tâm quản trị</span></div><div className="top-actions"><span className="status-dot" /> Hệ thống hoạt động</div></header><div className="page">{children}</div></main>{mobileOpen ? <div className="sidebar-overlay" onClick={() => setMobileOpen(false)} /> : null}</div>;
}

function Dashboard({ onNavigate }) {
  const [data, setData] = useState(null); const [users, setUsers] = useState([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.dashboard(), api.users({ limit: 5 })]).then(([metrics, result]) => { setData(metrics); setUsers(result.items); }).catch((err) => setError(err.message)); }, []);
  if (!data && !error) return <Spinner />;
  const metrics = [
    ['total_users', 'Người dùng', '♙', 'mint'], ['new_users', 'Người dùng mới', '+', 'blue'],
    ['active_users', 'Đang hoạt động', '✓', 'green'], ['total_transactions', 'Tổng giao dịch', '↕', 'amber'],
    ['total_wallets', 'Số lượng ví', '▣', 'purple'], ['total_categories', 'Danh mục mặc định', '◇', 'rose'],
  ];
  return <><PageTitle title="Tổng quan hệ thống" subtitle="Các chỉ số quan trọng được cập nhật từ dữ liệu thực." /><ErrorBox error={error} /><div className="metric-grid">{metrics.map(([key, title, icon, color]) => <div className="metric-card" key={key}><div className={`metric-icon ${color}`}>{icon}</div><div><span>{title}</span><strong>{Number(data?.[key] || 0).toLocaleString('vi-VN')}</strong><small>{key === 'new_users' ? 'Trong tháng này' : 'Toàn hệ thống'}</small></div></div>)}</div><div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><h2>Người dùng mới nhất</h2><p>Tài khoản đăng ký gần đây</p></div><button className="link-btn" onClick={() => onNavigate('users')}>Xem tất cả →</button></div><div className="table-wrap"><table><thead><tr><th>Người dùng</th><th>Tên đăng nhập</th><th>Ngày đăng ký</th><th>Trạng thái</th></tr></thead><tbody>{users.map((item) => <tr key={item.id}><td><div className="user-cell"><span className="avatar small-avatar">{initials(item.full_name)}</span><div><b>{item.full_name}</b><span>{item.email}</span></div></div></td><td>@{item.username}</td><td>{formatDate(item.created_at)}</td><td><Badge value={item.status} /></td></tr>)}</tbody></table></div></section><section className="panel quick-panel"><div className="panel-head"><div><h2>Việc cần chú ý</h2><p>Trạng thái vận hành</p></div></div><button onClick={() => onNavigate('feedback')}><span className="quick-icon amber">?</span><div><b>Phản hồi chưa xử lý</b><small>{data?.pending_feedback || 0} yêu cầu đang chờ</small></div><strong>→</strong></button><button onClick={() => onNavigate('notifications')}><span className="quick-icon blue">♢</span><div><b>Gửi thông báo</b><small>Thông tin tới người dùng</small></div><strong>→</strong></button><button onClick={() => onNavigate('statistics')}><span className="quick-icon green">▥</span><div><b>Xem tăng trưởng</b><small>Số liệu 12 tháng</small></div><strong>→</strong></button></section></div></>;
}

function Users() {
  const [result, setResult] = useState(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.users({ search, status, page, limit: 10 }).then(setResult).catch((err) => setError(err.message)).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [search, status, page]);
  const toggle = async (item) => { if (!confirm(`${item.status === 'active' ? 'Khóa' : 'Mở khóa'} tài khoản ${item.username}?`)) return; try { await api.setUserStatus(item.id, item.status === 'active' ? 'locked' : 'active'); load(); } catch (err) { setError(err.message); } };
  const remove = async (item) => { if (!confirm(`Xóa vĩnh viễn tài khoản ${item.username} và toàn bộ dữ liệu liên quan?`)) return; try { await api.removeUser(item.id); setSelected(null); load(); } catch (err) { setError(err.message); } };
  return <><PageTitle title="Quản lý người dùng" subtitle="Tìm kiếm, kiểm tra và quản lý trạng thái tài khoản." /><div className="toolbar"><div className="search-box">⌕<input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Tìm theo họ tên, email, username..." /></div><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></div><ErrorBox error={error} /><section className="panel"><div className="panel-head"><div><h2>Danh sách người dùng</h2><p>{result?.total || 0} tài khoản</p></div></div>{loading ? <Spinner /> : !result?.items.length ? <Empty>Không tìm thấy người dùng phù hợp</Empty> : <div className="table-wrap"><table><thead><tr><th>ID</th><th>Người dùng</th><th>Điện thoại</th><th>Ngày đăng ký</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{result.items.map((item) => <tr key={item.id}><td>#{item.id}</td><td><div className="user-cell"><span className="avatar small-avatar">{initials(item.full_name)}</span><div><b>{item.full_name}</b><span>{item.email} · @{item.username}</span></div></div></td><td>{item.phone || '—'}</td><td>{formatDate(item.created_at)}</td><td><Badge value={item.status} /></td><td><div className="row-actions"><button onClick={() => setSelected(item)}>Xem</button><button onClick={() => toggle(item)}>{item.status === 'active' ? 'Khóa' : 'Mở khóa'}</button><button className="danger-link" onClick={() => remove(item)}>Xóa</button></div></td></tr>)}</tbody></table></div>}<div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>← Trước</button><span>Trang {page} / {result?.total_pages || 1}</span><button disabled={page >= (result?.total_pages || 1)} onClick={() => setPage(page + 1)}>Sau →</button></div></section>{selected ? <Modal title="Thông tin người dùng" onClose={() => setSelected(null)}><div className="profile-summary"><div className="avatar large-avatar">{initials(selected.full_name)}</div><h3>{selected.full_name}</h3><Badge value={selected.status} /></div><dl className="detail-list"><div><dt>ID</dt><dd>#{selected.id}</dd></div><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Tên đăng nhập</dt><dd>@{selected.username}</dd></div><div><dt>Số điện thoại</dt><dd>{selected.phone || 'Chưa cập nhật'}</dd></div><div><dt>Ngày đăng ký</dt><dd>{formatDate(selected.created_at)}</dd></div></dl><div className="modal-actions"><button className="btn btn-secondary" onClick={() => toggle(selected)}>{selected.status === 'active' ? 'Khóa tài khoản' : 'Mở khóa tài khoản'}</button><button className="btn btn-danger" onClick={() => remove(selected)}>Xóa tài khoản</button></div></Modal> : null}</>;
}

function Categories() {
  const emptyForm = { name: '', type: 'expense', icon: '📌' };
  const [items, setItems] = useState([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const icons = ['🍜', '🛵', '🛍️', '🏠', '🧾', '📚', '🏥', '🎮', '💼', '💻', '🎁', '📈', '📌'];
  const load = () => api.categories().then(setItems).catch((err) => setError(err.message)).finally(() => setLoading(false)); useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setError(''); try { if (editing) await api.updateCategory(editing, form); else await api.createCategory(form); setEditing(null); setForm(emptyForm); load(); } catch (err) { setError(err.message); } };
  const edit = (item) => { setEditing(item.id); setForm({ name: item.name, type: item.type, icon: item.icon || '📌' }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const remove = async (item) => { if (!confirm(`Xóa danh mục mặc định “${item.name}”?`)) return; try { await api.removeCategory(item.id); load(); } catch (err) { setError(err.message); } };
  return <><PageTitle title="Danh mục hệ thống" subtitle="Danh mục mặc định sẽ được cấp cho tài khoản đăng ký mới." /><ErrorBox error={error} /><div className="form-layout"><form className="panel form-panel" onSubmit={submit}><div className="panel-head"><div><h2>{editing ? 'Cập nhật danh mục' : 'Thêm danh mục mặc định'}</h2><p>Người dùng vẫn có thể tạo danh mục riêng.</p></div></div><label>Tên danh mục<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ví dụ: Ăn uống" required /></label><label>Loại danh mục<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="expense">Chi tiêu</option><option value="income">Thu nhập</option></select></label><label>Biểu tượng</label><div className="icon-picker">{icons.map((icon) => <button type="button" className={form.icon === icon ? 'selected' : ''} onClick={() => setForm({ ...form, icon })} key={icon}>{icon}</button>)}</div><div className="form-actions"><button className="btn btn-primary">{editing ? 'Lưu thay đổi' : 'Thêm danh mục'}</button>{editing ? <button type="button" className="btn btn-secondary" onClick={() => { setEditing(null); setForm(emptyForm); }}>Hủy</button> : null}</div></form><section className="panel"><div className="panel-head"><div><h2>Danh mục hiện có</h2><p>{items.length} danh mục mặc định</p></div></div>{loading ? <Spinner /> : !items.length ? <Empty /> : <div className="category-list">{items.map((item) => <div className="category-row" key={item.id}><span className="category-icon">{item.icon || '📌'}</span><div><b>{item.name}</b><Badge value={item.type} /></div><div className="row-actions"><button onClick={() => edit(item)}>Sửa</button><button className="danger-link" onClick={() => remove(item)}>Xóa</button></div></div>)}</div>}</section></div></>;
}

function Notifications() {
  const emptyForm = { title: '', message: '', type: 'system', status: 'draft', send_now: false };
  const [items, setItems] = useState([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [filter, setFilter] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.notifications(filter).then(setItems).catch((err) => setError(err.message)).finally(() => setLoading(false)); }; useEffect(() => { load(); }, [filter]);
  const submit = async (event) => { event.preventDefault(); try { if (editing) await api.updateNotification(editing, form); else await api.createNotification(form); setEditing(null); setForm(emptyForm); load(); } catch (err) { setError(err.message); } };
  const edit = (item) => { setEditing(item.id); setForm({ title: item.title, message: item.message, type: item.type, status: item.status, send_now: false }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const send = async (item) => { if (!confirm(`Gửi “${item.title}” tới tất cả người dùng đang hoạt động?`)) return; try { const result = await api.sendNotification(item.id); alert(`${result.message} Số lượt gửi mới: ${result.sent}.`); load(); } catch (err) { setError(err.message); } };
  const remove = async (item) => { if (!confirm('Xóa thông báo này và các bản đã gửi tới người dùng?')) return; try { await api.removeNotification(item.id); load(); } catch (err) { setError(err.message); } };
  return <><PageTitle title="Thông báo hệ thống" subtitle="Soạn, gửi và quản lý thông báo chung tới người dùng." /><ErrorBox error={error} /><div className="form-layout"><form className="panel form-panel" onSubmit={submit}><div className="panel-head"><div><h2>{editing ? 'Chỉnh sửa thông báo' : 'Soạn thông báo mới'}</h2><p>Thông báo được lưu nháp trước khi gửi.</p></div></div><label>Tiêu đề<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Thông báo bảo trì hệ thống" maxLength={150} required /></label><label>Nội dung<textarea value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} placeholder="Nhập nội dung gửi đến người dùng..." maxLength={500} rows={5} required /></label><div className="two-fields"><label>Loại<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="system">Hệ thống</option><option value="maintenance">Bảo trì</option><option value="promotion">Tin mới</option></select></label>{editing ? <label>Trạng thái<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="draft">Bản nháp</option><option value="sent">Đã gửi</option><option value="archived">Lưu trữ</option></select></label> : null}</div>{!editing ? <label className="check"><input type="checkbox" checked={form.send_now} onChange={(event) => setForm({ ...form, send_now: event.target.checked })} /> Gửi ngay sau khi tạo</label> : null}<div className="form-actions"><button className="btn btn-primary">{editing ? 'Lưu thay đổi' : form.send_now ? 'Tạo và gửi ngay' : 'Lưu bản nháp'}</button>{editing ? <button type="button" className="btn btn-secondary" onClick={() => { setEditing(null); setForm(emptyForm); }}>Hủy</button> : null}</div></form><section className="panel"><div className="panel-head"><div><h2>Lịch sử thông báo</h2><p>Quản lý nội dung đã soạn và đã gửi</p></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Tất cả</option><option value="draft">Bản nháp</option><option value="sent">Đã gửi</option><option value="archived">Lưu trữ</option></select></div>{loading ? <Spinner /> : !items.length ? <Empty>Chưa có thông báo hệ thống</Empty> : <div className="notice-list">{items.map((item) => <article key={item.id}><div className="notice-top"><Badge value={item.status} /><time>{formatDate(item.created_at)}</time></div><h3>{item.title}</h3><p>{item.message}</p><div className="notice-actions">{item.status !== 'sent' ? <button className="btn btn-small btn-primary" onClick={() => send(item)}>Gửi tất cả</button> : null}<button className="btn btn-small btn-secondary" onClick={() => edit(item)}>Sửa</button><button className="btn btn-small btn-ghost-danger" onClick={() => remove(item)}>Xóa</button></div></article>)}</div>}</section></div></>;
}

function Feedback() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState(null); const [reply, setReply] = useState(''); const [status, setStatus] = useState('processing'); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); api.feedback(filter).then(setItems).catch((err) => setError(err.message)).finally(() => setLoading(false)); }; useEffect(() => { load(); }, [filter]);
  const open = (item) => { setSelected(item); setReply(item.admin_reply || ''); setStatus(item.status === 'pending' ? 'processing' : item.status); };
  const save = async () => { try { await api.updateFeedback(selected.id, { status, admin_reply: reply }); setSelected(null); load(); } catch (err) { setError(err.message); } };
  return <><PageTitle title="Phản hồi và hỗ trợ" subtitle="Tiếp nhận báo lỗi, góp ý và yêu cầu hỗ trợ từ người dùng." action={<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Tất cả trạng thái</option><option value="pending">Chờ xử lý</option><option value="processing">Đang xử lý</option><option value="resolved">Đã xử lý</option></select>} /><ErrorBox error={error} /><section className="panel">{loading ? <Spinner /> : !items.length ? <Empty>Chưa có phản hồi phù hợp</Empty> : <div className="feedback-list">{items.map((item) => <button key={item.id} onClick={() => open(item)}><span className={`feedback-icon ${item.type}`}>{item.type === 'bug' ? '!' : item.type === 'suggestion' ? '✦' : '?'}</span><div><div className="feedback-title"><b>{item.subject}</b><Badge value={item.status} /></div><p>{item.message}</p><small>{item.full_name} · {item.email} · {formatDate(item.created_at)}</small></div><strong>›</strong></button>)}</div>}</section>{selected ? <Modal title="Xử lý phản hồi" onClose={() => setSelected(null)} wide><div className="ticket-meta"><Badge value={selected.type} /><span>{selected.full_name} · {selected.email}</span><time>{formatDate(selected.created_at)}</time></div><h3>{selected.subject}</h3><div className="ticket-message">{selected.message}</div><div className="two-fields"><label>Trạng thái<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="pending">Chờ xử lý</option><option value="processing">Đang xử lý</option><option value="resolved">Đã xử lý</option></select></label></div><label>Nội dung trả lời<textarea rows={5} value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Nhập phản hồi cho người dùng..." /></label><div className="modal-actions"><button className="btn btn-secondary" onClick={() => setSelected(null)}>Hủy</button><button className="btn btn-primary" onClick={save}>Lưu xử lý</button></div></Modal> : null}</>;
}

function BarChart({ title, data, valueKey, color }) {
  const max = Math.max(1, ...data.map((item) => Number(item[valueKey])));
  return <section className="panel chart-panel"><div className="panel-head"><div><h2>{title}</h2><p>12 tháng gần nhất</p></div></div>{!data.length ? <Empty>Chưa đủ dữ liệu để tạo biểu đồ</Empty> : <div className="bar-chart">{data.map((item) => <div className="bar-item" key={item.month}><div className="bar-value">{item[valueKey]}</div><div className="bar-track"><div className={`bar ${color}`} style={{ height: `${Math.max(8, Number(item[valueKey]) / max * 100)}%` }} /></div><span>{item.month.slice(5)}</span></div>)}</div>}</section>;
}

function Statistics() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { api.statistics().then(setData).catch((err) => setError(err.message)); }, []);
  if (!data && !error) return <Spinner />;
  return <><PageTitle title="Thống kê hệ thống" subtitle="Dữ liệu tổng hợp, không hiển thị chi tiết tài chính cá nhân." /><ErrorBox error={error} /><div className="summary-strip"><div><span>Tổng người dùng</span><strong>{data?.total_users || 0}</strong></div><div><span>Người dùng mới trong 30 ngày</span><strong>{data?.new_users_30_days || 0}</strong></div><div><span>Tổng giao dịch</span><strong>{data?.total_transactions || 0}</strong></div></div><div className="charts-grid"><BarChart title="Tăng trưởng người dùng" data={data?.monthly_users || []} valueKey="users" color="green-bar" /><BarChart title="Số lượng giao dịch" data={data?.monthly_transactions || []} valueKey="transactions" color="blue-bar" /></div><div className="privacy-note"><span>◉</span><div><b>Nguyên tắc bảo vệ riêng tư</b><p>Trang quản trị chỉ sử dụng số lượng tổng hợp và không truy cập số dư, nội dung giao dịch hoặc mật khẩu của từng người dùng.</p></div></div></>;
}

function Account({ user, onUserChange, onLogout }) {
  const [profile, setProfile] = useState({ full_name: user.full_name, email: user.email, username: user.username, phone: user.phone || '' });
  const [password, setPassword] = useState({ current_password: '', new_password: '', confirm: '' }); const [sessions, setSessions] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const loadSessions = () => api.sessions().then(setSessions).catch((err) => setError(err.message)); useEffect(() => { loadSessions(); }, []);
  const saveProfile = async (event) => { event.preventDefault(); try { const data = await api.updateProfile(profile); onUserChange(data); setMessage('Đã cập nhật thông tin quản trị viên.'); } catch (err) { setError(err.message); } };
  const savePassword = async (event) => { event.preventDefault(); if (password.new_password !== password.confirm) return setError('Xác nhận mật khẩu mới không khớp.'); try { await api.changePassword(password); setPassword({ current_password: '', new_password: '', confirm: '' }); setMessage('Đã đổi mật khẩu và đăng xuất các phiên khác.'); loadSessions(); } catch (err) { setError(err.message); } };
  const revoke = async (item) => { if (!confirm('Đăng xuất phiên này?')) return; try { await api.revokeSession(item.id); if (item.current) return onLogout(false); loadSessions(); } catch (err) { setError(err.message); } };
  const revokeOthers = async () => { try { await api.revokeOthers(); setMessage('Đã đăng xuất tất cả phiên khác.'); loadSessions(); } catch (err) { setError(err.message); } };
  return <><PageTitle title="Tài khoản quản trị" subtitle="Cập nhật hồ sơ, bảo mật và quản lý các phiên đăng nhập." /><ErrorBox error={error} />{message ? <div className="success-box">{message}</div> : null}<div className="account-grid"><form className="panel form-panel" onSubmit={saveProfile}><div className="panel-head"><div><h2>Thông tin cá nhân</h2><p>Thông tin hiển thị của quản trị viên</p></div></div><label>Họ và tên<input value={profile.full_name} onChange={(event) => setProfile({ ...profile, full_name: event.target.value })} required /></label><label>Email<input type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} required /></label><label>Tên đăng nhập<input value={profile.username} onChange={(event) => setProfile({ ...profile, username: event.target.value })} required /></label><label>Số điện thoại<input value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /></label><button className="btn btn-primary">Lưu thông tin</button></form><form className="panel form-panel" onSubmit={savePassword}><div className="panel-head"><div><h2>Đổi mật khẩu</h2><p>Nên sử dụng mật khẩu khó đoán</p></div></div><label>Mật khẩu hiện tại<input type="password" value={password.current_password} onChange={(event) => setPassword({ ...password, current_password: event.target.value })} required /></label><label>Mật khẩu mới<input type="password" minLength={6} value={password.new_password} onChange={(event) => setPassword({ ...password, new_password: event.target.value })} required /></label><label>Xác nhận mật khẩu mới<input type="password" value={password.confirm} onChange={(event) => setPassword({ ...password, confirm: event.target.value })} required /></label><button className="btn btn-primary">Đổi mật khẩu</button></form></div><section className="panel session-panel"><div className="panel-head"><div><h2>Phiên đăng nhập</h2><p>Kiểm tra thiết bị đang truy cập tài khoản admin</p></div><button className="btn btn-secondary btn-small" onClick={revokeOthers}>Đăng xuất phiên khác</button></div><div className="session-list">{sessions.map((item) => <div key={item.id}><span className="session-icon">▣</span><div><b>{item.user_agent?.includes('Mobile') ? 'Thiết bị di động' : 'Trình duyệt máy tính'} {item.current ? <em>Phiên hiện tại</em> : null}</b><span>IP: {item.ip_address || 'Không xác định'} · Hoạt động: {formatDate(item.last_used_at)}</span></div><button className="danger-link" onClick={() => revoke(item)}>Đăng xuất</button></div>)}</div></section></>;
}

export default function App() {
  const [user, setUser] = useState(null); const [checking, setChecking] = useState(true); const [section, setSection] = useState('dashboard');
  useEffect(() => { if (!session.get()) return setChecking(false); api.profile().then((data) => { if (data.role === 'admin') setUser(data); else session.clear(); }).catch(() => session.clear()).finally(() => setChecking(false)); }, []);
  const logout = async (callApi = true) => { if (callApi) await api.logout().catch(() => {}); session.clear(); setUser(null); };
  const page = useMemo(() => ({ dashboard: <Dashboard onNavigate={setSection} />, users: <Users />, categories: <Categories />, notifications: <Notifications />, feedback: <Feedback />, statistics: <Statistics />, account: <Account user={user} onUserChange={setUser} onLogout={logout} /> })[section], [section, user]);
  if (checking) return <div className="splash"><div className="brand-mark">₫</div><Spinner /></div>;
  if (!user) return <Login onLogin={setUser} />;
  return <Shell user={user} section={section} setSection={setSection} onLogout={logout}>{page}</Shell>;
}
