import { useCallback,useState } from 'react';
import { Pressable,Text,View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { categoryService,transactionService,walletService } from '@/dichvu';
import type { Category,Transaction,TransactionType,Wallet } from '@/kieudulieu';
import { Button,Card,EmptyState,Field,Header,Loading,Screen } from '@/thanhphan/dungchung/UI';
import { TransactionItem } from '@/thanhphan/giaodich/TransactionItem';
import { Colors } from '@/hangso/colors';

type Period='all'|'week'|'month'|'year'|'custom';
function datesFor(period:Period){const now=new Date();if(period==='all'||period==='custom')return{};const end=now.toISOString().slice(0,10);const start=new Date(now);if(period==='week')start.setDate(now.getDate()-6);if(period==='month')start.setDate(1);if(period==='year'){start.setMonth(0);start.setDate(1)}return{start_date:start.toISOString().slice(0,10),end_date:end}}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={{paddingHorizontal:12,paddingVertical:9,borderRadius:12,backgroundColor:active?Colors.primary:Colors.surface,borderWidth:1,borderColor:active?Colors.primary:Colors.border}}><Text style={{color:active?Colors.white:Colors.text,fontWeight:'700',fontSize:13}}>{label}</Text></Pressable>}

export default function Transactions(){
  const [items,setItems]=useState<Transaction[]>([]);const [wallets,setWallets]=useState<Wallet[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [loading,setLoading]=useState(true);const [showFilters,setShowFilters]=useState(false);const [search,setSearch]=useState('');const [type,setType]=useState<TransactionType>();const [walletId,setWalletId]=useState<number>();const [categoryId,setCategoryId]=useState<number>();const [period,setPeriod]=useState<Period>('all');const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const dates=period==='custom'?{start_date:startDate||undefined,end_date:endDate||undefined}:datesFor(period);const [transactions,walletResult,categoryResult]=await Promise.all([transactionService.list({search:search||undefined,type,wallet_id:walletId,category_id:categoryId,...dates}),walletService.list(),categoryService.list()]);setItems(transactions.data);setWallets(walletResult.data);setCategories(categoryResult.data);}finally{setLoading(false)}},[search,type,walletId,categoryId,period,startDate,endDate]);
  useFocusEffect(useCallback(()=>{load()},[load]));
  const clear=()=>{setType(undefined);setWalletId(undefined);setCategoryId(undefined);setPeriod('all');setStartDate('');setEndDate('')};
  return <Screen><Header title="Giao dịch" subtitle="Tìm kiếm và lọc toàn bộ khoản thu chi"/><Field label="Tìm kiếm" value={search} onChangeText={setSearch} placeholder="Danh mục, ví hoặc ghi chú..."/><Button title={showFilters?'Ẩn bộ lọc':'Mở bộ lọc'} variant="secondary" onPress={()=>setShowFilters(value=>!value)}/>{showFilters?<Card style={{gap:13}}><Text style={{fontWeight:'800',color:Colors.text}}>Loại giao dịch</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}><Chip label="Tất cả" active={!type} onPress={()=>setType(undefined)}/><Chip label="Chi tiêu" active={type==='expense'} onPress={()=>setType('expense')}/><Chip label="Thu nhập" active={type==='income'} onPress={()=>setType('income')}/></View><Text style={{fontWeight:'800',color:Colors.text}}>Thời gian</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}>{([['all','Tất cả'],['week','Tuần'],['month','Tháng'],['year','Năm'],['custom','Tùy chọn']] as [Period,string][]).map(([value,label])=><Chip key={value} label={label} active={period===value} onPress={()=>setPeriod(value)}/>)}</View>{period==='custom'?<View style={{gap:10}}><Field label="Từ ngày" value={startDate} onChangeText={setStartDate} placeholder="YYYY-MM-DD"/><Field label="Đến ngày" value={endDate} onChangeText={setEndDate} placeholder="YYYY-MM-DD"/></View>:null}<Text style={{fontWeight:'800',color:Colors.text}}>Ví</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}><Chip label="Mọi ví" active={!walletId} onPress={()=>setWalletId(undefined)}/>{wallets.map(wallet=><Chip key={wallet.id} label={wallet.name} active={walletId===wallet.id} onPress={()=>setWalletId(wallet.id)}/>)}</View><Text style={{fontWeight:'800',color:Colors.text}}>Danh mục</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:7}}><Chip label="Mọi danh mục" active={!categoryId} onPress={()=>setCategoryId(undefined)}/>{categories.filter(category=>!type||category.type===type).map(category=><Chip key={category.id} label={`${category.icon||'•'} ${category.name}`} active={categoryId===category.id} onPress={()=>setCategoryId(category.id)}/>)}</View><Button title="Xóa bộ lọc" variant="secondary" onPress={clear}/></Card>:null}{loading?<Loading/>:items.length?items.map(item=><TransactionItem key={item.id} item={item}/>):<EmptyState title="Không có giao dịch phù hợp"/>}</Screen>;
}
