import type { PropsWithChildren,ReactNode } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type KeyboardTypeOptions,type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';import { Colors } from '@/hangso/colors';
export function Screen({children,scroll=true}:PropsWithChildren<{scroll?:boolean}>){const content=<View style={styles.content}>{children}</View>;return <SafeAreaView edges={['top']} style={styles.safe}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}>{content}</ScrollView>:content}</SafeAreaView>}
export function Header({title,subtitle,right}:{title:string;subtitle?:string;right?:ReactNode}){return <View style={styles.header}><View style={{flex:1}}><Text style={styles.title}>{title}</Text>{subtitle?<Text style={styles.subtitle}>{subtitle}</Text>:null}</View>{right}</View>}
export function Card({children,style}:PropsWithChildren<{style?:ViewStyle}>){return <View style={[styles.card,style]}>{children}</View>}
export function Button({title,onPress,loading=false,variant='primary',disabled=false}:{title:string;onPress:()=>void;loading?:boolean;variant?:'primary'|'secondary'|'danger';disabled?:boolean}){return <Pressable disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.button,variant==='secondary'&&styles.secondary,variant==='danger'&&styles.danger,(pressed||disabled)&&{opacity:.65}]}>{loading?<ActivityIndicator color={variant==='secondary'?Colors.primary:Colors.white}/>:<Text style={[styles.buttonText,variant==='secondary'&&{color:Colors.primary}]}>{title}</Text>}</Pressable>}
export function Field({label,error,...props}:{label:string;error?:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;secureTextEntry?:boolean;keyboardType?:KeyboardTypeOptions;multiline?:boolean}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor="#9AA6A2" style={[styles.input,props.multiline&&{height:88,textAlignVertical:'top'},error&&{borderColor:Colors.expense}]} {...props}/>{error?<Text style={styles.error}>{error}</Text>:null}</View>}
export function EmptyState({title='Chưa có dữ liệu',description='Hãy thêm dữ liệu đầu tiên để bắt đầu.'}:{title?:string;description?:string}){return <View style={styles.empty}><Text style={{fontSize:35}}>◌</Text><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.subtitle}>{description}</Text></View>}
export function Loading(){return <View style={styles.loading}><ActivityIndicator size="large" color={Colors.primary}/><Text style={styles.subtitle}>Đang tải dữ liệu...</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},scroll:{flexGrow:1},content:{width:'100%',maxWidth:720,alignSelf:'center',padding:20,paddingBottom:110,gap:16},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:4},title:{fontSize:26,fontWeight:'800',color:Colors.text},subtitle:{fontSize:14,color:Colors.muted,lineHeight:20},card:{backgroundColor:Colors.surface,borderRadius:20,padding:18,borderWidth:1,borderColor:Colors.border,shadowColor:'#0B332A',shadowOpacity:.06,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2},button:{minHeight:52,borderRadius:15,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center',paddingHorizontal:20},secondary:{backgroundColor:Colors.primarySoft,borderWidth:1,borderColor:'#B9E1D6'},danger:{backgroundColor:Colors.expense},buttonText:{color:Colors.white,fontSize:16,fontWeight:'700'},field:{gap:7},label:{fontSize:14,fontWeight:'700',color:Colors.text},input:{height:52,borderRadius:14,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,paddingHorizontal:15,color:Colors.text,fontSize:16},error:{fontSize:12,color:Colors.expense},empty:{alignItems:'center',padding:30,gap:7},emptyTitle:{fontSize:17,fontWeight:'700',color:Colors.text},loading:{flex:1,minHeight:280,alignItems:'center',justifyContent:'center',gap:12}});
export const ui=styles;
